### ISSUE TITLE
compatibility issue with Pytorch 1.3

### ISSUE THREAD

**Issue by sunglyoungKim** [facebookresearch/DeepSDF#30]
Hello, I am trying to run train code but it seems like there is a backward compatibility issue in the train code.

Traceback (most recent call last):
  File "train_deep_sdf.py", line 595, in <module>
    main_function(args.experiment_directory, args.continue_from, int(args.batch_split))
  File "train_deep_sdf.py", line 515, in main_function
    chunk_loss.backward()
  File "/.local/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: leaf variable has been moved into the graph interior

The easy solution is using Pytorch 1.2 but I wonder if you can debug this error and it would be grateful!

Thank you

**Comment by sunglyoungKim** [comment]
Ignore the issue. It works now.
