### ISSUE TITLE
Cuda Out of memory Error

### ISSUE THREAD

**Issue by SirNova01** [facebookresearch/DeepSDF#43]
Thanks for the amazing work
I got the following error when I run  "python3 train_deep_sdf.py -e examples/sofas"
What should i do pls?

DeepSdf - INFO - Experiment description: 
['This experiment learns a shape representation for sofas ', 'using data from ShapeNet version 2.']
DeepSdf - INFO - training with 1 GPU(s)
DeepSdf - INFO - There are 1628 scenes
DeepSdf - INFO - starting from epoch 1
DeepSdf - INFO - Number of decoder parameters: 1843195
DeepSdf - INFO - Number of shape code parameters: 416768 (# codes 1628, code dim 256)
DeepSdf - INFO - epoch 1...
Traceback (most recent call last):
  File "train_deep_sdf.py", line 595, in <module>
    main_function(args.experiment_directory, args.continue_from, int(args.batch_split))
  File "train_deep_sdf.py", line 499, in main_function
    pred_sdf = decoder(input)
  File "/home/pgstud/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pgstud/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/pgstud/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pgstud/DeepSDF/networks/deep_sdf_decoder.py", line 104, in forward
    x = F.dropout(x, p=self.dropout_prob, training=self.training)
  File "/home/pgstud/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 807, in dropout
    else _VF.dropout(input, p, training))
RuntimeError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 7.93 GiB total capacity; 5.02 GiB already allocated; 1.27 GiB free; 5.02 GiB reserved in total by PyTorch)
(base) pgstud@pgstud-HP-EliteDesk-800-G4-Twr-IDS-APJ:~/DeepSDF$

**Comment by 1995YogeshSharma** [comment]
Try reducing the batch size 
"ScenesPerBatch" attribute in specs.json

**Comment by zhuyinheng** [comment]
`ScenesPerBatch=16` works for 11G GPU memory

**Comment by yhijioka** [comment]
`train_deep_sdf.py` has a optional argument, which is `--batch_split`.
If you run the script with this argument, it separates batch by given value and compute errors each oens, then summarize them as an error of the batch.
If you haven’t used it, try it!

```sh
python3 train_deep_sdf.py -e examples/sofas --batch_split 4
```

**Comment by novauto-nju** [comment]
I modified the batchsize, but I encountered the following `problems：`(py37) zenghui@psdz:~/DeepSDF$ python train_deep_sdf.py -e examples/chairs --bat                                                                                                 ch_split 4
DeepSdf - INFO - ['This experiment learns a shape representation for chairs ', '                                                                                                 using data from ShapeNet version 2.']
DeepSdf - INFO - training with 3 GPU(s)
DeepSdf - INFO - There are 67 scenes
DeepSdf - INFO - starting from epoch 1
DeepSdf - INFO - Number of decoder parameters: 1843195
DeepSdf - INFO - Number of shape code parameters: 17152 (# codes 67, code dim 256)
DeepSdf - INFO - epoch 1...
Traceback (most recent call last):
  File "train_deep_sdf.py", line 591, in <module>
    main_function(args.experiment_directory, args.continue_from, int(args.batch_split))
  File "train_deep_sdf.py", line 511, in main_function
    chunk_loss.backward()
  File "/home/zenghui/.conda/envs/py37/lib/python3.7/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zenghui/.conda/envs/py37/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: leaf variable has been moved into the graph interior
``
